// Thin fetch wrapper shared by every frontend/src/api/*.ts module. Requests
// are same-origin under /api — in dev, vite.config.ts proxies that prefix to
// the FastAPI backend; in production the backend serves the SPA and the API
// from the same origin, so no base URL configuration is needed here.

export class ApiError extends Error {
  readonly status: number
  /** The parsed error body, if any — callers that need more than `message`
   * (e.g. the auth store reading `setup_required` off a 401) read it here
   * rather than every error shape growing its own constructor field. */
  readonly details: unknown

  constructor(status: number, message: string, details?: unknown) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.details = details
  }
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  // A `FormData` body is passed to fetch untouched and, crucially, *without* a
  // `Content-Type` header of our own: the multipart boundary is generated by
  // the browser and only appears in the header fetch writes itself. Setting
  // `multipart/form-data` by hand omits the boundary, and the server then reads
  // a body it cannot parse — which surfaces as a 422 about a missing field
  // rather than anything pointing at the header.
  const isForm = body instanceof FormData
  const response = await fetch(`/api${path}`, {
    method,
    headers: body === undefined || isForm ? undefined : { 'Content-Type': 'application/json' },
    body: body === undefined || isForm ? (body as FormData | undefined) : JSON.stringify(body),
    credentials: 'same-origin',
  })

  // 204 No Content and other empty bodies have nothing to parse.
  const text = await response.text()
  const data = text.length > 0 ? JSON.parse(text) : undefined

  if (!response.ok) {
    const message =
      (data && typeof data === 'object' && 'message' in data && typeof data.message === 'string'
        ? data.message
        : undefined) ?? response.statusText
    throw new ApiError(response.status, message, data)
  }

  return data as T
}

export const api = {
  get: <T>(path: string) => request<T>('GET', path),
  post: <T>(path: string, body?: unknown) => request<T>('POST', path, body),
  /** `POST` of a `multipart/form-data` body — file uploads. Spelled as its own
   * method so a call site says which wire format it is sending, and so nothing
   * accidentally hands a `FormData` to `post` expecting it to be JSON. */
  postForm: <T>(path: string, form: FormData) => request<T>('POST', path, form),
  // `put` where the route takes a full-replacement body (every field required,
  // omissions reset to their default), `patch` where it genuinely patches only
  // the keys present. The backend draws that line per resource, so the two
  // cannot be used interchangeably — a mismatch is a 405.
  put: <T>(path: string, body?: unknown) => request<T>('PUT', path, body),
  patch: <T>(path: string, body?: unknown) => request<T>('PATCH', path, body),
  delete: <T>(path: string) => request<T>('DELETE', path),
}
