"""Baseline schema.

The whole schema in one revision: the rewrite starts from an empty database
(there is no data to preserve), so the old app's migration history collapses
here rather than being carried across the rename.

Autogenerated from `app.models` and then adjusted in one place: the
`prompts.deployed_version_id` -> `prompt_versions.id` foreign key is a cycle
(`prompt_versions.prompt_id` points back), so it is declared `use_alter=True`
on the model and added here as a separate `ALTER TABLE` once both tables
exist — and dropped again first thing on the way down.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-13 15:20:46.893552

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
    )
    op.create_index(
        "customers_name_lower_idx", "customers", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "machines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column("cpu", sa.Text(), nullable=True),
        sa.Column("ram", sa.Text(), nullable=True),
        sa.Column("gpu", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_machines_customer_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machines")),
    )
    op.create_index(op.f("ix_machines_customer_id"), "machines", ["customer_id"], unique=False)
    op.create_table(
        "test_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_test_groups_customer_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_groups")),
    )
    op.create_index(
        "test_groups_customer_name_idx", "test_groups", ["customer_id", "name"], unique=False
    )
    op.create_table(
        "toolsets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.Text(), server_default="manual", nullable=False),
        sa.Column("mcp_url", sa.Text(), nullable=True),
        sa.Column("mcp_headers", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_toolsets_customer_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_toolsets")),
    )
    op.create_index("toolsets_customer_name_idx", "toolsets", ["customer_id", "name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("oidc_subject", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), server_default="viewer", nullable=False),
        sa.Column("active_customer_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_customer_id"],
            ["customers.id"],
            name=op.f("fk_users_active_customer_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("oidc_subject", name=op.f("uq_users_oidc_subject")),
    )
    op.create_index(
        "users_email_lower_idx", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("display_prefix", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_tokens_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_tokens_token_hash")),
    )
    op.create_index(op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False)
    op.create_table(
        "machine_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column(
            "currently_loaded", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
            name=op.f("fk_machine_models_machine_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_machine_models")),
        sa.UniqueConstraint(
            "machine_id", "model_id", name=op.f("uq_machine_models_machine_id_model_id")
        ),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("deployed_version_id", sa.Integer(), nullable=True),
        sa.Column("deployed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deployed_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_prompts_customer_id"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["deployed_by"], ["users.id"], name=op.f("fk_prompts_deployed_by"), ondelete="SET NULL"
        ),
        # fk_prompts_deployed_version_id is added below, once prompt_versions exists.
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
    )
    op.create_index("prompts_customer_name_idx", "prompts", ["customer_id", "name"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.Integer(), nullable=True),
        sa.Column("machine_snapshot", sa.Text(), nullable=False),
        sa.Column("model_id", sa.Text(), nullable=False),
        sa.Column("params", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("group_names", sa.Text(), nullable=False),
        sa.Column("llm_info", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_runs_customer_id"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"], ["machines.id"], name=op.f("fk_runs_machine_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(op.f("ix_runs_customer_id"), "runs", ["customer_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "tools",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("toolset_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parameters_json", sa.Text(), server_default="{}", nullable=False),
        sa.Column("mock_response", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("source", sa.Text(), server_default="manual", nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["toolset_id"], ["toolsets.id"], name=op.f("fk_tools_toolset_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tools")),
        sa.UniqueConstraint("toolset_id", "name", name=op.f("uq_tools_toolset_id_name")),
    )
    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("baseline_run_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_run_id"],
            ["runs.id"],
            name=op.f("fk_prompt_versions_baseline_run_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_prompt_versions_created_by"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
            name=op.f("fk_prompt_versions_prompt_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_versions")),
        sa.UniqueConstraint(
            "prompt_id", "version", name=op.f("uq_prompt_versions_prompt_id_version")
        ),
    )
    op.create_foreign_key(
        op.f("fk_prompts_deployed_version_id"),
        "prompts",
        "prompt_versions",
        ["deployed_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "test_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("expected_output", sa.Text(), nullable=True),
        sa.Column("prompt_id", sa.Integer(), nullable=True),
        sa.Column("mode", sa.Text(), server_default="append", nullable=False),
        sa.Column("custom_text", sa.Text(), nullable=True),
        sa.Column("tool_mode", sa.Text(), server_default="none", nullable=False),
        sa.Column("tool_choice", sa.Text(), nullable=True),
        sa.Column("max_turns", sa.Integer(), server_default=sa.text("6"), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["test_groups.id"],
            name=op.f("fk_test_cases_group_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"], ["prompts.id"], name=op.f("fk_test_cases_prompt_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
    )
    op.create_index(op.f("ix_test_cases_group_id"), "test_cases", ["group_id"], unique=False)
    op.create_table(
        "run_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("test_case_id", sa.Integer(), nullable=True),
        sa.Column("prompt_version_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("group_name", sa.Text(), nullable=False),
        sa.Column("test_case_title", sa.Text(), nullable=False),
        sa.Column("test_case_text", sa.Text(), nullable=False),
        sa.Column("expected_output", sa.Text(), nullable=True),
        sa.Column("effective_prompt_text", sa.Text(), nullable=True),
        sa.Column("tools_snapshot", sa.Text(), nullable=True),
        sa.Column("tool_mode", sa.Text(), server_default="none", nullable=False),
        sa.Column("tool_choice", sa.Text(), nullable=True),
        sa.Column("max_turns", sa.Integer(), server_default=sa.text("6"), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("transcript_json", sa.Text(), nullable=True),
        sa.Column("turns_json", sa.Text(), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=True),
        sa.Column("tool_call_count", sa.Integer(), nullable=True),
        sa.Column("stopped_reason", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("tokens_per_sec", sa.Double(), nullable=True),
        sa.Column(
            "tokens_estimated", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("rating", sa.Text(), nullable=True),
        sa.Column("rating_note", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["prompt_version_id"],
            ["prompt_versions.id"],
            name=op.f("fk_run_results_prompt_version_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_results_run_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
            name=op.f("fk_run_results_test_case_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_results")),
    )
    op.create_index(
        "run_results_prompt_version_id_idx", "run_results", ["prompt_version_id"], unique=False
    )
    op.create_index("run_results_run_id_idx", "run_results", ["run_id"], unique=False)
    op.create_index("run_results_test_case_id_idx", "run_results", ["test_case_id"], unique=False)
    op.create_table(
        "test_case_toolsets",
        sa.Column("test_case_id", sa.Integer(), nullable=False),
        sa.Column("toolset_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
            name=op.f("fk_test_case_toolsets_test_case_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["toolset_id"],
            ["toolsets.id"],
            name=op.f("fk_test_case_toolsets_toolset_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("test_case_id", "toolset_id", name=op.f("pk_test_case_toolsets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Breaks the cycle: prompt_versions cannot be dropped while prompts still
    # references it.
    op.drop_constraint(op.f("fk_prompts_deployed_version_id"), "prompts", type_="foreignkey")
    op.drop_table("test_case_toolsets")
    op.drop_index("run_results_test_case_id_idx", table_name="run_results")
    op.drop_index("run_results_run_id_idx", table_name="run_results")
    op.drop_index("run_results_prompt_version_id_idx", table_name="run_results")
    op.drop_table("run_results")
    op.drop_index(op.f("ix_test_cases_group_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_table("prompt_versions")
    op.drop_table("tools")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_runs_customer_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index("prompts_customer_name_idx", table_name="prompts")
    op.drop_table("prompts")
    op.drop_table("machine_models")
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index("users_email_lower_idx", table_name="users")
    op.drop_table("users")
    op.drop_index("toolsets_customer_name_idx", table_name="toolsets")
    op.drop_table("toolsets")
    op.drop_index("test_groups_customer_name_idx", table_name="test_groups")
    op.drop_table("test_groups")
    op.drop_index(op.f("ix_machines_customer_id"), table_name="machines")
    op.drop_table("machines")
    op.drop_index("customers_name_lower_idx", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
