"""A markdown corpus a model can retrieve from: the `documents` table.

One table, and it is a **second child of `toolsets`** sitting beside `tools`.
That placement is the whole design: a `documents` toolset is selected on a test
case exactly like a manual or MCP one, its three retrieval tools
(`list_documents`, `search_documents`, `read_document`) are real `tools` rows so
`assert_tool_config`'s collision and `enabled` checks, `tools_snapshot` and the
toolset detail UI all keep working untouched, and the corpus those tools read is
the `documents` rows of that same toolset.

**No `customer_id` column**, deliberately, the same as `tools` and
`endpoint_models`: scope is inherited through `toolset_id` and expressed once in
`scope_through_parent`. A second, independently-writable answer to "whose corpus
is this" could disagree with the first, and it would break sharing — a global
toolset borrowed by another engagement has to bring its documents with it, which
inheritance gives for free and a `customer_id` here would refuse. `app.scope`'s
`_SHAREABLE` map therefore needs no entry: only root tables appear in it.

`content_tsv` is a **STORED generated column**, which forces two things worth
recording:

* The expression must be **IMMUTABLE**, so it is the two-argument
  `to_tsvector('simple', ...)`. The one-argument `to_tsvector(text)` reads
  `default_text_search_config` at call time, is therefore only STABLE, and
  Postgres rejects it in a generated column outright.
* The configuration is `'simple'`, not `'english'`. These are a consultancy's
  customer documents and they are frequently German; English stemming over
  German text degrades retrieval in a way that surfaces in `/results` as a
  *model* failure, which is the one misattribution this app exists to prevent.
  `simple` folds case and stems nothing, which is the honest default across a
  mixed-language corpus. Every query against the column must name the same
  configuration.

The GIN index on `content_tsv` is what makes `websearch_to_tsquery` a search
rather than a sequential scan; `UNIQUE (toolset_id, path)` makes `path` the
`read_document` key, unique within its corpus and free to repeat across
toolsets.

There is no corpus versioning or freezing in this revision — a run's
`tools_snapshot` carries `document_count` and `corpus_updated_at` as a
forward-compat crumb, and both live inside JSON that is already being written,
so nothing schema-level is needed for them.

Written by hand rather than autogenerated: `sa.Computed` and the GIN index are
exactly the two things autogenerate renders unreliably.

Revision ID: 0007_documents
Revises: 0006_endpoint_platform_params
Create Date: 2026-08-17

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007_documents"
down_revision: str | None = "0006_endpoint_platform_params"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Kept literal here rather than imported from `app.models.toolsets`: a
#: migration describes the schema at one point in history, and must not change
#: meaning because a later revision edits the model it was generated from.
TSV_EXPRESSION = "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, ''))"


def upgrade() -> None:
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("toolset_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(TSV_EXPRESSION, persisted=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["toolset_id"],
            ["toolsets.id"],
            name=op.f("fk_documents_toolset_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("toolset_id", "path", name=op.f("uq_documents_toolset_id_path")),
    )
    op.create_index(
        "documents_content_tsv_idx",
        "documents",
        ["content_tsv"],
        unique=False,
        postgresql_using="gin",
    )


def downgrade() -> None:
    op.drop_index("documents_content_tsv_idx", table_name="documents")
    op.drop_table("documents")
